apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-cache-config
  namespace: thingsboard
  labels:
    name: tb-cache-config
data:
  CACHE_TYPE: redis
  REDIS_CONNECTION_TYPE: standalone
  REDIS_HOST: tb-redis-master.tb-redis.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_USE_DEFAULT_POOL_CONFIG: "false"
  REDIS_PASSWORD: "redis"
